config/routes.rb
Rails.application.routes.draw do
  root to: 'cocktails#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cocktails do
    resources :doses, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, :through => :doses

  validates :name, presence: true, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, :cocktail, :ingredient, presence: true
  validates :cocktail, uniqueness: { scope: [:ingredient] }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    #@ingredient = Ingredient.find()
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktails_params)
    @cocktail.save
    redirect_to @cocktail
  end

  def edit
    @cocktail = Cocktail.find(params[:id])
  end

  def update
    @cocktail = Cocktail.find(params[:id])
    @cocktail.update(cocktails_params)
    redirect_to @cocktail
  end

  def destroy
    @cocktail = Cocktail.find(params[:id])
    @cocktail.destroy
    redirect_to @cocktail
  end

  private

  def cocktails_params
  params.require(:cocktail).permit(:name)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(cocktail: @cocktail)
    @ingredients = Ingredient.all
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(doses_params)
    @dose.cocktail = @cocktail
    @dose.save!
    redirect_to cocktail_path(@cocktail)
  end

  private

  def doses_params
    params.require(:dose).permit(:ingredient_id, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/edit.html.erb
<h1>Edit cocktail</h1>

<%= simple_form_for(@cocktail) do |f| %>
    <%= f.input :name %>
    <%= f.submit 'Create' %>
<% end %>

app/views/cocktails/index.html.erb
<div id='banner'>
  <h1>Mister Cocktail</h1>
</div>

<div class='container'>
  <div class="row">
    <% @cocktails.each do |cocktail| %>
    <div class="col-xs-12 col-sm-4">
      <div class="card">
        <div class="card-description">
          <%= link_to cocktail.name, cocktail_path(cocktail) %>
        </div>
        <div class="card-delete">
          <%= link_to '', cocktail_path(cocktail),
              method: :delete,
                data: { confirm: 'Are you sure?' },
                  class: "far fa-trash-alt" %>
        </div>
      </div>
    </div>
    <% end %>

<%= link_to 'Add a new cocktail', new_cocktail_path, class: 'btn btn-primary' %>
  </div>
</div>

app/views/cocktails/new.html.erb
<h1>New cocktail</h1>

<%= simple_form_for(@cocktail) do |f| %>
    <%= f.input :name %>
    <%= f.submit 'Create' %>
<% end %>

app/views/cocktails/show.html.erb
<h1><%= @cocktail.name %></h1>

<% @cocktail.doses.each do |dose| %>
<%= dose.description %>
<%= dose.ingredient.name %>

<% end %>

<%= link_to 'Back to the list', cocktails_path, class: 'btn btn-primary' %>
<%= link_to 'Edit cocktail', edit_cocktail_path, class: 'btn btn-primary' %>
<%= link_to 'Add ingredient', new_cocktail_dose_path(@cocktail) %>

app/views/doses/new.html.erb
<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.input :description %>
  <%= f.association :ingredient %>
  <%= f.submit  %>
<% end %>

<%#= form_for (@dose) do |f| %>
<%#= f.text_field :description %>
<%#= f.submit %>
<%#= end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
    <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
  </body>
</html>